/**
 * Embodied method landscape — structured completeness / platform data.
 * @typedef {'Isaac / Omniverse'|'SAPIEN / ManiSkill'|'MuJoCo / robosuite'|'AI2-THOR'|'OmniGibson / BEHAVIOR'|'Drake / Multi-export'|'Multi-platform / Asset Factory'|'Mixed / Framework'|'Infrastructure / Benchmark'} PlatformFamily
 */
(function (global) {
  'use strict';

  /** @type {import('./embodiedMethodLandscape.types').MethodScore[]} */
  var embodiedMethods = [
    {
      id: 'embodiedgen',
      name: 'EmbodiedGen: Towards a Generative 3D World Engine for Embodied Intelligence',
      shortName: 'EmbodiedGen',
      year: 2025,
      type: 'Foundation Model Orchestration',
      platformFamily: 'Multi-platform / Asset Factory',
      platforms: ['Isaac Lab', 'MuJoCo', 'SAPIEN', 'OpenAI Gym'],
      assetFormats: ['URDF', 'mesh', '3DGS'],
      completenessLevel: 'C2 Sim-Ready',
      compatibilityScore: 5,
      compatibilityLabel: 'High',
      computeScore: 4,
      computeLabel: 'Medium–High',
      hardware: '论文未明确报告 GPU 型号和数量',
      scores: { task: 1, worldAsset: 5, simReady: 5, rewardProgram: 1, dataGeneration: 2, policyBenchmark: 2, realTransfer: 1 },
      role: 'Sim-Ready Asset / World Factory',
      strength: '通过多基础模型编排生成 URDF、mesh、3DGS、纹理、关节物体和场景资产，跨平台资产生产能力强。',
      limitation: '更偏资产与世界生产线；任务、reward、系统性策略训练与真实迁移仍不是核心验证。',
      citation: 'Wang et al. EmbodiedGen: Towards a Generative 3D World Engine for Embodied Intelligence. arXiv:2506.10600, 2025.',
      url: 'https://arxiv.org/abs/2506.10600',
    },
    {
      id: 'sage',
      name: 'SAGE: Scalable Agentic 3D Scene Generation for Embodied AI',
      shortName: 'SAGE',
      year: 2026,
      type: 'Agentic World Generation',
      platformFamily: 'Isaac / Omniverse',
      platforms: ['Isaac Sim'],
      assetFormats: ['USD', 'simulation-ready scene'],
      completenessLevel: 'C4 Policy-Ready',
      compatibilityScore: 3,
      compatibilityLabel: 'Medium',
      computeScore: 4,
      computeLabel: 'High',
      hardware: '公开页面未清晰报告 GPU 型号和数量',
      scores: { task: 5, worldAsset: 4, simReady: 5, rewardProgram: 2, dataGeneration: 4, policyBenchmark: 4, realTransfer: 1 },
      role: 'Task-conditioned environment generation + policy training',
      strength: '从语言任务生成 simulation-ready 环境，并通过 critic 闭环和策略训练验证连接到 Policy-Ready。',
      limitation: '强绑定 Isaac 生态；真实机器人迁移仍需要进一步验证。',
      citation: 'SAGE: Scalable Agentic 3D Scene Generation for Embodied AI. arXiv:2602.10116, 2026.',
      url: 'https://arxiv.org/abs/2602.10116',
      notes: '年份与公开信息请在上线前再次核对。',
    },
    {
      id: 'scenesmith',
      name: 'SceneSmith: A Unified Framework for Generating Simulation-Ready Indoor Scenes',
      shortName: 'SceneSmith',
      year: 2026,
      type: 'Agentic World Generation',
      platformFamily: 'Drake / Multi-export',
      platforms: ['Drake', 'MuJoCo', 'PyBullet', 'Isaac Sim', 'Genesis', 'Blender'],
      assetFormats: ['SDFormat', 'MJCF', 'USD'],
      completenessLevel: 'C2 Sim-Ready',
      compatibilityScore: 5,
      compatibilityLabel: 'High',
      computeScore: 5,
      computeLabel: 'High',
      hardware: '报告使用 8× NVIDIA L40S；完整 pipeline 约 45GB+ VRAM',
      scores: { task: 2, worldAsset: 5, simReady: 5, rewardProgram: 1, dataGeneration: 1, policyBenchmark: 2, realTransfer: 0 },
      role: 'Cross-platform simulation-ready indoor scene generation',
      strength: '跨平台导出能力强，可连接 Drake、MuJoCo、PyBullet、Isaac Sim 等平台。',
      limitation: '更偏 simulation-ready 场景生成；任务、reward、真实迁移链条较弱。',
      citation: 'SceneSmith: A Unified Framework for Generating Simulation-Ready Indoor Scenes. arXiv:2602.09153, 2026.',
      url: 'https://arxiv.org/abs/2602.09153',
      notes: '年份与公开信息请在上线前再次核对。',
    },
    {
      id: 'gen2sim',
      name: 'Gen2Sim: Scaling up Robot Learning in Simulation with Generative Models',
      shortName: 'Gen2Sim',
      year: 2023,
      type: 'Task / Reward Generation',
      platformFamily: 'Isaac / Omniverse',
      platforms: ['Isaac Gym'],
      assetFormats: ['URDF', 'task code', 'reward function'],
      completenessLevel: 'C4 Policy-Ready',
      compatibilityScore: 3,
      compatibilityLabel: 'Medium',
      computeScore: 3,
      computeLabel: 'Medium',
      hardware: '论文摘要与页面未清晰报告 GPU 型号和数量',
      scores: { task: 4, worldAsset: 4, simReady: 4, rewardProgram: 5, dataGeneration: 3, policyBenchmark: 4, realTransfer: 1 },
      role: 'Asset + task + reward + RL bridge',
      strength: '自动生成 3D 资产、任务描述、任务分解和 reward functions，并连接到 RL。',
      limitation: 'reward 正确性、真实迁移和复杂长程任务仍需验证。',
      citation: 'Katara et al. Gen2Sim: Scaling up Robot Learning in Simulation with Generative Models. arXiv:2310.18308, 2023.',
      url: 'https://arxiv.org/abs/2310.18308',
    },
    {
      id: 'robogen',
      name: 'RoboGen: Towards Unleashing Infinite Data for Automated Robot Learning via Generative Simulation',
      shortName: 'RoboGen',
      year: 2024,
      type: 'Agentic World Generation',
      platformFamily: 'Mixed / Framework',
      platforms: ['generative simulation framework', 'planning tools', 'RL tools'],
      assetFormats: ['task', 'scene', 'training supervision'],
      completenessLevel: 'C4 Policy-Ready',
      compatibilityScore: 3,
      compatibilityLabel: 'Medium',
      computeScore: 3,
      computeLabel: 'Medium',
      hardware: '论文页面未清晰报告 GPU 型号和数量',
      scores: { task: 5, worldAsset: 3, simReady: 3, rewardProgram: 4, dataGeneration: 4, policyBenchmark: 4, realTransfer: 1 },
      role: 'Propose-generate-learn automated robot learning loop',
      strength: '覆盖任务提出、环境生成、任务分解、训练监督和策略学习。',
      limitation: '平台与资产质量依赖具体实现链路，真实迁移验证较弱。',
      citation: 'Wang et al. RoboGen: Towards Unleashing Infinite Data for Automated Robot Learning via Generative Simulation. ICML 2024 / arXiv:2311.01455.',
      url: 'https://arxiv.org/abs/2311.01455',
    },
    {
      id: 'gensim2',
      name: 'GenSim2: Scaling Robot Data Generation with Multi-modal and Reasoning LLMs',
      shortName: 'GenSim2',
      year: 2024,
      type: 'Task / Reward Generation',
      platformFamily: 'SAPIEN / ManiSkill',
      platforms: ['SAPIEN'],
      assetFormats: ['task code', 'demo data', 'articulated tasks'],
      completenessLevel: 'C4 Policy-Ready',
      compatibilityScore: 3,
      compatibilityLabel: 'Medium',
      computeScore: 3,
      computeLabel: 'Medium',
      hardware: '论文页面未清晰报告 GPU 型号和数量',
      scores: { task: 5, worldAsset: 2, simReady: 3, rewardProgram: 4, dataGeneration: 5, policyBenchmark: 4, realTransfer: 3 },
      role: 'Task code + demonstration data + sim2real',
      strength: '使用多模态和推理 LLM 生成复杂仿真任务与 demonstration data。',
      limitation: '环境与资产生成不是核心贡献，依赖任务代码与 solver 质量。',
      citation: 'Hua et al. GenSim2: Scaling Robot Data Generation with Multi-modal and Reasoning LLMs. arXiv:2410.03645, 2024.',
      url: 'https://arxiv.org/abs/2410.03645',
    },
    {
      id: 'mimicgen',
      name: 'MimicGen: A Data Generation System for Scalable Robot Learning Using Human Demonstrations',
      shortName: 'MimicGen',
      year: 2023,
      type: 'Demonstration / Rollout Generation',
      platformFamily: 'MuJoCo / robosuite',
      platforms: ['robosuite', 'MuJoCo', 'Isaac Gym Factory'],
      assetFormats: ['demonstration trajectories'],
      completenessLevel: 'C0 Component-Level',
      compatibilityScore: 3,
      compatibilityLabel: 'Medium',
      computeScore: 2,
      computeLabel: 'Low–Medium',
      hardware: '论文页面未清晰报告 GPU 型号和数量',
      scores: { task: 0, worldAsset: 0, simReady: 2, rewardProgram: 0, dataGeneration: 5, policyBenchmark: 4, realTransfer: 1 },
      role: 'Few demos to large-scale demonstrations',
      strength: '从少量人类示范自动扩展大规模 demonstration，用于 imitation learning。',
      limitation: '不负责环境生成和任务生成，依赖原始 demo 质量。',
      citation: 'Mandlekar et al. MimicGen: A Data Generation System for Scalable Robot Learning Using Human Demonstrations. CoRL 2023 / arXiv:2310.17596.',
      url: 'https://arxiv.org/abs/2310.17596',
    },
    {
      id: 'robotwin',
      name: 'RoboTwin: Dual-Arm Robot Benchmark with Generative Digital Twins',
      shortName: 'RoboTwin',
      year: 2025,
      type: 'Demonstration / Rollout Generation',
      platformFamily: 'SAPIEN / ManiSkill',
      platforms: ['SAPIEN'],
      assetFormats: ['digital twins', 'expert data', 'benchmark tasks'],
      completenessLevel: 'C4 Policy-Ready',
      compatibilityScore: 3,
      compatibilityLabel: 'Medium',
      computeScore: 3,
      computeLabel: 'Medium',
      hardware: '官方文档强调 NVIDIA GPU + SAPIEN；具体论文 GPU 数量需核对',
      scores: { task: 3, worldAsset: 3, simReady: 4, rewardProgram: 3, dataGeneration: 5, policyBenchmark: 4, realTransfer: 2 },
      role: 'Dual-arm expert data and benchmark',
      strength: '面向双臂操作，结合 generative digital twins、专家数据和 benchmark。',
      limitation: '任务域偏双臂操作，真实迁移仍需更多验证。',
      citation: 'Mu et al. RoboTwin: Dual-Arm Robot Benchmark with Generative Digital Twins. CVPR 2025 / arXiv:2409.02920.',
      url: 'https://arxiv.org/abs/2409.02920',
    },
    {
      id: 'robotwin2',
      name: 'RoboTwin 2.0: A Scalable Data Generator and Benchmark with Generative Digital Twins',
      shortName: 'RoboTwin 2.0',
      year: 2025,
      type: 'Demonstration / Rollout Generation',
      platformFamily: 'SAPIEN / ManiSkill',
      platforms: ['SAPIEN'],
      assetFormats: ['expert data', 'benchmark', 'task program'],
      completenessLevel: 'C4 Policy-Ready',
      compatibilityScore: 3,
      compatibilityLabel: 'Medium',
      computeScore: 3,
      computeLabel: 'Medium',
      hardware: '官方文档强调 NVIDIA GPU + SAPIEN；具体论文 GPU 数量需核对',
      scores: { task: 3, worldAsset: 3, simReady: 4, rewardProgram: 3, dataGeneration: 5, policyBenchmark: 4, realTransfer: 2 },
      role: 'Scalable bimanual data generator and benchmark',
      strength: '集成 expert data generation pipeline、50-task benchmark 和自动 task program synthesis。',
      limitation: '主要面向双臂操作，跨平台兼容度中等。',
      citation: 'Mu et al. RoboTwin 2.0: A Scalable Data Generator and Benchmark with Generative Digital Twins. arXiv:2506.18088, 2025.',
      url: 'https://arxiv.org/abs/2506.18088',
    },
    {
      id: 'maniskill3',
      name: 'ManiSkill3: GPU Parallelized Robotics Simulation and Rendering for Generalizable Embodied AI',
      shortName: 'ManiSkill3',
      year: 2025,
      type: 'Benchmark / Training Platform',
      platformFamily: 'SAPIEN / ManiSkill',
      platforms: ['SAPIEN', 'ManiSkill'],
      assetFormats: ['Gym-style tasks', 'demonstrations', 'benchmark environments'],
      completenessLevel: 'C4 Policy-Ready',
      compatibilityScore: 3,
      compatibilityLabel: 'Medium',
      computeScore: 3,
      computeLabel: 'Medium',
      hardware: '论文报告 GPU 并行仿真与渲染可达到 30,000+ FPS；具体 GPU 型号需核对',
      scores: { task: 1, worldAsset: 1, simReady: 5, rewardProgram: 3, dataGeneration: 3, policyBenchmark: 5, realTransfer: 2 },
      role: 'High-throughput manipulation simulator and benchmark',
      strength: 'GPU 并行仿真、渲染与操作 benchmark 强，适合 RL / IL 训练。',
      limitation: '不是上游环境生成或任务生成系统。',
      citation: 'Tao et al. ManiSkill3: GPU Parallelized Robotics Simulation and Rendering for Generalizable Embodied AI. RSS 2025 / arXiv:2410.00425.',
      url: 'https://arxiv.org/abs/2410.00425',
    },
    {
      id: 'behavior1k',
      name: 'BEHAVIOR-1K: A Human-Centered Embodied AI Benchmark with 1,000 Everyday Activities',
      shortName: 'BEHAVIOR-1K',
      year: 2024,
      type: 'Benchmark / Training Platform',
      platformFamily: 'OmniGibson / BEHAVIOR',
      platforms: ['OmniGibson', 'Omniverse'],
      assetFormats: ['BDDL', 'activity tasks', 'OmniGibson assets'],
      completenessLevel: 'C4 Policy-Ready',
      compatibilityScore: 2,
      compatibilityLabel: 'Medium–Low',
      computeScore: 4,
      computeLabel: 'High',
      hardware: '论文页面未清晰报告单一 GPU 配置；Omniverse / OmniGibson 通常系统较重',
      scores: { task: 3, worldAsset: 3, simReady: 4, rewardProgram: 3, dataGeneration: 3, policyBenchmark: 4, realTransfer: 0 },
      role: 'Everyday activity benchmark',
      strength: '提供 1000 个日常活动级任务和高保真物理仿真 benchmark。',
      limitation: '更偏评测基座，不强调自动生成全链条或真实迁移。',
      citation: 'BEHAVIOR-1K: A Human-Centered Embodied AI Benchmark with 1,000 Everyday Activities and Realistic Simulation. arXiv:2403.09227, 2024.',
      url: 'https://arxiv.org/abs/2403.09227',
    },
    {
      id: 'rialto',
      name: 'RialTo: Real-to-Sim-to-Real Reinforcement Learning for Robot Manipulation',
      shortName: 'RialTo',
      year: 2024,
      type: 'Real2Sim2Real',
      platformFamily: 'Isaac / Omniverse',
      platforms: ['Isaac Sim', 'Orbit-style pipeline'],
      assetFormats: ['digital twin', 'Isaac simulation'],
      completenessLevel: 'C5 Real-Ready',
      compatibilityScore: 2,
      compatibilityLabel: 'Medium–Low',
      computeScore: 4,
      computeLabel: 'High',
      hardware: '报告使用 NVIDIA RTX 2080 或 RTX 3090；单任务约 2 天级别流程',
      scores: { task: 2, worldAsset: 4, simReady: 5, rewardProgram: 2, dataGeneration: 4, policyBenchmark: 4, realTransfer: 5 },
      role: 'Real-to-Sim-to-Real closed loop',
      strength: '从真实场景构建 digital twin，在仿真中 RL robustification，再回到真实机器人。',
      limitation: '单场景定制成本较高，平台绑定较重。',
      citation: 'RialTo: Real-to-Sim-to-Real Reinforcement Learning for Robot Manipulation. arXiv:2403.03949, 2024.',
      url: 'https://arxiv.org/abs/2403.03949',
    },
    {
      id: 're3sim',
      name: 'Re3Sim: Learning Realistic Robot Policies in 3D Real-to-Sim Environments',
      shortName: 'Re3Sim',
      year: 2025,
      type: 'Real-to-Sim Reconstruction',
      platformFamily: 'Isaac / Omniverse',
      platforms: ['Isaac Sim', 'PhysX', '3D Gaussian Splatting'],
      assetFormats: ['mesh collision', '3DGS rendering'],
      completenessLevel: 'C5 Real-Ready',
      compatibilityScore: 2,
      compatibilityLabel: 'Medium–Low',
      computeScore: 5,
      computeLabel: 'High',
      hardware: '报告使用 8× RTX 4090',
      scores: { task: 1, worldAsset: 4, simReady: 5, rewardProgram: 1, dataGeneration: 5, policyBenchmark: 4, realTransfer: 5 },
      role: 'High-fidelity real-to-sim data generation',
      strength: '结合真实场景重建、3DGS 渲染、物理仿真和专家数据，实现 zero-shot sim2real。',
      limitation: '算力成本高，强绑定 Isaac / 3DGS / PhysX 管线。',
      citation: 'Re3Sim: Learning Realistic Robot Policies in 3D Real-to-Sim Environments. arXiv:2502.08645, 2025.',
      url: 'https://arxiv.org/abs/2502.08645',
    },
    {
      id: 'digitalcousins',
      name: 'ACDC: Automated Creation of Digital Cousins for Robust Policy Learning',
      shortName: 'Digital Cousins / ACDC',
      year: 2024,
      type: 'Real2Sim2Real',
      platformFamily: 'OmniGibson / BEHAVIOR',
      platforms: ['OmniGibson', 'BEHAVIOR asset ecosystem'],
      assetFormats: ['interactive digital cousin scenes'],
      completenessLevel: 'C5 Real-Ready',
      compatibilityScore: 2,
      compatibilityLabel: 'Medium–Low',
      computeScore: 4,
      computeLabel: 'High',
      hardware: '官方实现建议 24GB+ VRAM 的 NVIDIA RTX GPU',
      scores: { task: 1, worldAsset: 4, simReady: 4, rewardProgram: 1, dataGeneration: 4, policyBenchmark: 4, realTransfer: 5 },
      role: 'Affordance-similar digital cousins for zero-shot sim2real',
      strength: '不追求精确 digital twin，而生成 affordance 相似场景，提高真实迁移鲁棒性。',
      limitation: '平台生态较重，真实迁移链路复杂。',
      citation: 'ACDC: Automated Creation of Digital Cousins for Robust Policy Learning. arXiv:2410.07408, 2024.',
      url: 'https://arxiv.org/abs/2410.07408',
    },
    {
      id: 'procthor',
      name: 'ProcTHOR: Large-Scale Embodied AI Using Procedural Generation',
      shortName: 'ProcTHOR',
      year: 2022,
      type: 'Layout / Procedural Generation',
      platformFamily: 'AI2-THOR',
      platforms: ['AI2-THOR'],
      assetFormats: ['procedural houses', 'AI2-THOR scenes'],
      completenessLevel: 'C2 Sim-Ready',
      compatibilityScore: 2,
      compatibilityLabel: 'Medium–Low',
      computeScore: 2,
      computeLabel: 'Low–Medium',
      hardware: '论文页面未清晰报告 GPU 型号和数量',
      scores: { task: 1, worldAsset: 4, simReady: 4, rewardProgram: 1, dataGeneration: 2, policyBenchmark: 4, realTransfer: 0 },
      role: 'Large-scale procedural houses for embodied AI',
      strength: '程序化生成大规模可交互房屋环境，适合 embodied AI benchmark。',
      limitation: '视觉与物理简化，真实迁移不强。',
      citation: 'Deitke et al. ProcTHOR: Large-Scale Embodied AI Using Procedural Generation. arXiv:2206.06994, 2022.',
      url: 'https://arxiv.org/abs/2206.06994',
    },
    {
      id: 'holodeck',
      name: 'Holodeck: Language Guided Generation of 3D Embodied AI Environments',
      shortName: 'Holodeck',
      year: 2023,
      type: 'Layout / Procedural Generation',
      platformFamily: 'AI2-THOR',
      platforms: ['AI2-THOR'],
      assetFormats: ['AI2-THOR scenes', 'Objaverse assets'],
      completenessLevel: 'C2 Sim-Ready',
      compatibilityScore: 2,
      compatibilityLabel: 'Medium–Low',
      computeScore: 2,
      computeLabel: 'Low–Medium',
      hardware: '论文页面未清晰报告 GPU 型号和数量',
      scores: { task: 3, worldAsset: 4, simReady: 4, rewardProgram: 1, dataGeneration: 2, policyBenchmark: 3, realTransfer: 0 },
      role: 'Language-guided embodied AI environment generation',
      strength: '使用语言 prompt 和资产库生成 AI2-THOR 可交互环境。',
      limitation: '受限于资产库和 AI2-THOR 生态，真实迁移弱。',
      citation: 'Yang et al. Holodeck: Language Guided Generation of 3D Embodied AI Environments. arXiv:2312.09067, 2023.',
      url: 'https://arxiv.org/abs/2312.09067',
    },
    {
      id: 'isaaclab',
      name: 'Isaac Lab: A GPU-Accelerated Simulation Framework for Multi-Modal Robot Learning',
      shortName: 'Isaac Lab',
      year: 2025,
      type: 'Infrastructure',
      platformFamily: 'Isaac / Omniverse',
      platforms: ['Isaac Sim', 'Isaac Lab', 'Omniverse'],
      assetFormats: ['USD', 'Isaac tasks', 'RL environments'],
      completenessLevel: 'C4 Policy-Ready',
      compatibilityScore: 2,
      compatibilityLabel: 'Medium–Low',
      computeScore: 4,
      computeLabel: 'High',
      hardware: 'NVIDIA GPU 生态；具体取决于任务规模',
      scores: { task: 0, worldAsset: 1, simReady: 5, rewardProgram: 3, dataGeneration: 3, policyBenchmark: 5, realTransfer: 2 },
      role: 'Industrial-grade robot learning simulation framework',
      strength: '强大的 Isaac / Omniverse 生态、GPU 仿真、RL / IL 支持。',
      limitation: '本身不负责上游场景和资产生成。',
      citation: 'Mittal et al. Isaac Lab: A GPU-Accelerated Simulation Framework for Multi-Modal Robot Learning. arXiv:2511.04831, 2025.',
      url: 'https://arxiv.org/abs/2511.04831',
      notes: '年份与公开信息请在上线前再次核对。',
    },
  ];

  var platformColors = {
    'Isaac / Omniverse': '#ef4444',
    'SAPIEN / ManiSkill': '#f97316',
    'MuJoCo / robosuite': '#8b5cf6',
    'AI2-THOR': '#64748b',
    'OmniGibson / BEHAVIOR': '#06b6d4',
    'Drake / Multi-export': '#22c55e',
    'Multi-platform / Asset Factory': '#2563eb',
    'Mixed / Framework': '#a855f7',
    'Infrastructure / Benchmark': '#14b8a6',
  };

  var platformCenters = {
    'Isaac / Omniverse': { x: 75, y: 70 },
    'SAPIEN / ManiSkill': { x: 60, y: 40 },
    'MuJoCo / robosuite': { x: 35, y: 35 },
    'AI2-THOR': { x: 25, y: 70 },
    'OmniGibson / BEHAVIOR': { x: 80, y: 30 },
    'Drake / Multi-export': { x: 45, y: 85 },
    'Multi-platform / Asset Factory': { x: 50, y: 95 },
    'Mixed / Framework': { x: 50, y: 60 },
    'Infrastructure / Benchmark': { x: 70, y: 50 },
  };

  var DIMENSIONS = [
    { key: 'task', label: 'Task Generation', short: 'Task', desc: '是否生成任务、目标状态、子任务、约束。' },
    { key: 'worldAsset', label: 'World / Asset', short: 'World / Asset', desc: '是否生成场景、布局、物体、纹理、关节资产或 digital twin。' },
    { key: 'simReady', label: 'Sim-Ready', short: 'Sim-Ready', desc: '是否能进入仿真器，具备 URDF / USD / MJCF / mesh / collision / reset-step API。' },
    { key: 'rewardProgram', label: 'Reward / Program', short: 'Reward / Program', desc: '是否生成 reward、success metric、task code、reset / step / check_success。' },
    { key: 'dataGeneration', label: 'Data Generation', short: 'Data', desc: '是否生成专家示范、rollout、offline RL 数据、随机化数据。' },
    { key: 'policyBenchmark', label: 'Policy / Benchmark', short: 'Policy / Benchmark', desc: '是否支持 IL / RL / benchmark / evaluation protocol。' },
    { key: 'realTransfer', label: 'Real Transfer', short: 'Real Transfer', desc: '是否支持 Sim2Real / Real2Sim2Real / 真实机器人验证。' },
  ];

  var SCORE_COLORS = ['#64748b', '#bfdbfe', '#60a5fa', '#22d3ee', '#fb923c', '#e11d48'];

  var DEFAULT_RADAR_IDS = ['embodiedgen', 'sage', 'gen2sim', 'robogen', 'rialto', 're3sim', 'maniskill3'];

  var PLATFORM_FAMILIES = Object.keys(platformColors);

  var METHOD_TYPES = [
    'Agentic World Generation',
    'Foundation Model Orchestration',
    'Asset / World Factory',
    'Task / Reward Generation',
    'Demonstration / Rollout Generation',
    'Benchmark / Training Platform',
    'Real2Sim2Real',
    'Layout / Procedural Generation',
    'Real-to-Sim Reconstruction',
    'Infrastructure',
  ];

  var COMPLETENESS_LEVELS = [
    'C0 Component-Level',
    'C1 World-Level',
    'C2 Sim-Ready',
    'C3 Task / Program-Ready',
    'C4 Policy-Ready',
    'C5 Real-Ready',
  ];

  var COMPUTE_LEVELS = ['Low', 'Low–Medium', 'Medium', 'Medium–High', 'High'];

  function getAverageCompleteness(method) {
    var s = method.scores;
    return (
      s.task +
      s.worldAsset +
      s.simReady +
      s.rewardProgram +
      s.dataGeneration +
      s.policyBenchmark +
      s.realTransfer
    ) / 7;
  }

  function getCompletenessLabel(avg) {
    if (avg >= 4.2) return 'Very High';
    if (avg >= 3.3) return 'High';
    if (avg >= 2.5) return 'Medium';
    if (avg >= 1.6) return 'Low–Medium';
    return 'Low';
  }

  function getMethodById(id) {
    for (var i = 0; i < embodiedMethods.length; i++) {
      if (embodiedMethods[i].id === id) return embodiedMethods[i];
    }
    return null;
  }

  global.EmbodiedMethodLandscape = {
    embodiedMethods: embodiedMethods,
    platformColors: platformColors,
    platformCenters: platformCenters,
    DIMENSIONS: DIMENSIONS,
    SCORE_COLORS: SCORE_COLORS,
    DEFAULT_RADAR_IDS: DEFAULT_RADAR_IDS,
    PLATFORM_FAMILIES: PLATFORM_FAMILIES,
    METHOD_TYPES: METHOD_TYPES,
    COMPLETENESS_LEVELS: COMPLETENESS_LEVELS,
    COMPUTE_LEVELS: COMPUTE_LEVELS,
    getAverageCompleteness: getAverageCompleteness,
    getCompletenessLabel: getCompletenessLabel,
    getMethodById: getMethodById,
  };
})(typeof window !== 'undefined' ? window : globalThis);
